services:
  serial:
    build:
      context: .
    container_name: serial
    restart: unless-stopped
    networks:
      network:
        aliases:
          - backend
    devices:
      - /dev/ttyACM0:/dev/ttyACM0

networks:
  network:
    external: false
    name: orangepila_network