services:
  mosquitto:
    image: docker.io/library/eclipse-mosquitto:latest
    container_name: mosquitto
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./mosquitto/config/
        target: /mosquitto/config/
      - type: bind
        source: ./mosquitto/log/
        target: /mosquitto/log/
      - type: volume
        source: data
        target: /mosquitto/data/
    ports:
      - target: 1883
        published: 1883
        protocol: tcp
        mode: host
      - target: 9001
        published: 9001
        protocol: tcp
        mode: host
    networks:
      network:
        aliases:
          - backend

  serial:
    build:
      context: ./serialreader
    container_name: serial
    restart: always
    networks:
      network:
        aliases:
          - backend
    devices:
      - /dev/ttyACM0:/dev/ttyACM0

volumes:
  data:
    name: "mqtt-broker-data"

networks:
  network:
    external: false
    name: orangepila_network