services:
  mosquitto:
    image: docker.io/library/eclipse-mosquitto:latest
    container_name: mosquitto
    restart: always
    volumes:
      - type: bind
        source: ./mosquitto/config/
        target: /mosquitto/config/
      - type: bind
        source: ./mosquitto/log/
        target: /mosquitto/log/
      - type: volume
        source: data
        target: /mosquitto/data/
    ports:
      - target: 1883
        published: 1883
        protocol: tcp
        mode: host
      - target: 9001
        published: 9001
        protocol: tcp
        mode: host
    networks:
      network:
        aliases:
          - backend

  serial:
    build:
      context: ./serialreader
    container_name: serial
    restart: always
    networks:
      network:
        aliases:
          - backend
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    healthcheck:
      test: [ "CMD-SHELL", "ls /dev/ttyACM0 |wc -l" ]
      interval: 10s
      timeout: 5s
      retries: 500
      start_period: 10s

  nakarte:
    build:
      context: ./nakarte
    container_name: nakarte
    restart: always
    networks:
      network:
        aliases:
          - backend
    ports:
      - target: 8080
        published: 80
        protocol: tcp
        mode: host
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host

  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    networks:
      network:
        aliases:
          - backend
    ports:
      - target: 3306
        published: 3306
        protocol: tcp
        mode: host
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: pila
      MYSQL_USER: pila
      MYSQL_PASSWORD: pila
    volumes:
      - ./mysql/data:/var/lib/mysql/

  api:
    build:
      context: ./api
    container_name: api
    restart: always
    networks:
      network:
        aliases:
          - backend
    ports:
      - target: 8081
        published: 8081
        protocol: tcp
        mode: host

volumes:
  data:
    name: "mqtt-broker-data"

networks:
  network:
    external: false
    name: orangepila_network